version: '3.2'

services:
  node:
    build:
      context: ./docker/node
    volumes:
      - .:/srv
    working_dir: /srv
    environment:
      DOMAIN_NAME: "default:smartcycle.local"
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0
    volumes:
      - .:/srv
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
